#### Stored Motivational Crypto Quotes for Crypto Discord Bot ####
##################################################################

quotes = [
    "I see Bitcoin as ultimately becoming a reserve currency for banks, playing much the same role as gold did in the early days of banking. Banks could issue digital cash with greater anonymity and lighter weight, more efficient transactions. – Hal Finney",
    "Any time a country transitioned to a fiat currency, they collapsed. That’s just world history; you don’t have to know about cryptocurrency to know that. – Nipsey Hussle",
    "If the cryptocurrency market overall or a digital asset is solving a problem, it’s going to drive some value. –  Brad Garlinghouse",
    "Whenever the price of cryptocurrency is rallying, people start spending a lot more. – Erik Voorhees",
    "We are seeing more managed money and, to an extent, institutional money entering the [crypto] space. Anecdotally speaking, I know of many people who are working at hedge funds or other investment managers who are trading cryptocurrency personally, the question is, when do people start doing it with their firms and funds?",
    "I am very excited about the prospect of using cryptocurrency, not just as a money equivalent, but using it as a way to earn something as a result of doing some type of work. – William Mougayar",
    "What value does cryptocurrency add? No one’s been able to answer that question to me. – Steve Eisman",
    "Bitcoin is here to stay. There would be a hacker uproar to anyone who attempted to take credit for the patent of cryptocurrency. And I wouldn’t want to be on the receiving end of hacker fury. – Adam Draper",
    "I am very intrigued by Bitcoin. It has all the signs. Paradigm shift, hackers love it, yet it is described as a toy. Just like microcomputers. – Paul Graham",
    "Blockchain is the tech. Bitcoin is merely the first mainstream manifestation of its potential. – Marc Kenigsberg",
    "As the value goes up, heads start to swivel and skeptics begin to soften. Starting a new currency is easy, anyone can do it. The trick is getting people to accept it because it is their use that gives the “money” value. – Adam B. Levine",
    "Bitcoin will do to banks what email did to the postal industry – Rick Falkvinge",
    "Bitcoin is a technological tour de force. – Bill Gates Bitcoin quote",
    "Well, I think it is working. There may be other currencies like it that may be even better. But in the meantime, there’s a big industry around Bitcoin— People have made fortunes off Bitcoin, some have lost money. It is volatile, but people make money off of volatility too. – Richard Branson",
    "[Bitcoin] is a remarkable cryptographic achievement… The ability to create something which is not duplicable in the digital world has enormous value…Lot’s of people will build businesses on top of that. – Eric Schmidt",
    "PayPal had these goals of creating a new currency. We failed at that, and we just created a new payment system. I think Bitcoin has succeeded on the level of a new currency, but the payment system is somewhat lacking. It’s very hard to use, and that’s the big challenge on the Bitcoin side. – Peter Thiel",
    "Bitcoin actually has the balance and incentives center, and that is why it is starting to take off.  – Julian Assange",
    "Bitcoin is the beginning of something great: a currency without a government, something necessary and imperative.” – Nassim Taleb, Author and Risk Analyst",
    "Bitcoin, and the ideas behind it, will be a disrupter to the traditional notions of currency. In the end, currency will be better for it. – Edmund Moy, 38th Director of the United States Mint",
    "Right now Bitcoin feels like the Internet before the browser. – Wences Casares",
    "[Bitcoin] is a very exciting development, it might lead to a world currency. I think over the next decade it will grow to become one of the most important ways to pay for things and transfer assets. – Kim Dotcom, CEO of MegaUpload",
    "The Federal Reserve simply does not have authority to supervise or regulate Bitcoin in any way. – Janet Yellen, former chair of the US Federal Reserve",
    "EVERY informed person needs to know about Bitcoin because it might be one of the world’s most important developments. – Leon Louw, two-time Nobel Peace Prize nominee",
    "Bitcoin may be the TCP/IP of money. – Paul Buchheit",
    "Cryptographical solutions might with great propriety be introduced into academies as the means of giving tone to the most important of the powers of the mind.  – Edgar Allan Poe",
    "It’s gold for nerds. – Stephan Colbert, Comedian",
    "If [Bitcoin does] not [reach $500.000 by the end of 2020], I will eat my d*ck on national television. – John McAfee – founder McAfee antivirus",
    "I understand the political ramifications of [bitcoin] and I think that the government should stay out of them and they should be perfectly legal. – Ron Paul, Republican Texas Congressman and former candidate for US President",
    "I think the fact that within the bitcoin universe an algorithm replaces the functions of [the government] is actually pretty cool. I am a big fan of Bitcoin. – Al Gore, 45th Vice President of the United States",
    "Cryptocurrency is such a powerful concept that it can almost overturn governments – Charles Lee, Creator of Litecoin",
    "The reason we are all here is that the current financial system is outdated. – Charlie Shrem – founder & CEO Bitinstant",
    "There are 3 eras of currency: Commodity based, politically based, and now, math-based. – Chris Dixon",
    "At their core, cryptocurrencies are built around the principle of a universal, inviolable ledger, one that is made fully public and is constantly being verified by these high-powered computers, each essentially acting independently of the others.  – Paul Vigna",
    "I love seeing new services constantly starting to accept Bitcoin. Bitcoin is really becoming “the currency of the Internet.” I’m most concerned by possible government reactions to Bitcoin. They can’t destroy Bitcoin, but they could really slow things down by making exchange much more difficult. – Michael Marquardt",
    "Bitcoin is Money Over Internet Protocol. – Tony Gallippi",
    "If Satoshi had released Bitcoin 10 yrs. earlier, 9/11 would never have happened. – Max Keiser",
    "One must acknowledge with cryptography no amount of violence will ever solve a math problem. – Jacob Appelbaum",
    "At its core, bitcoin is a smart currency, designed by very forward-thinking engineers. It eliminates the need for banks, gets rid of credit card fees, currency exchange fees, money transfer fees, and reduces the need for lawyers in transitions… all good things – Peter Diamandis",
    "When I first heard about Bitcoin, I thought it was impossible. How can you have a purely digital currency? Can’t I just copy your hard drive and have your bitcoins? I didn’t understand how that could be done, and then I looked into it and it was brilliant. – Jeff Garzik",
    "The governments of the world have spent hundreds and hundreds of trillions of dollars bailing out a decaying, dickensian, outmoded system called banking when the solution to the future of finance is peer-to-peer. It’s going to be alternative currencies like Bitcoin and it’s not actually going to be a banking system as we had before 2008.  – Patrick Young",
    "We have elected to put our money and faith in a mathematical framework that is free of politics and human error. – Tyler Winklevoss",
    "Hey, obviously this is a very interesting time to be in Bitcoin center now, but if you guys want to argue over whether this is reality or not, one Bitcoin will feed over 40 homeless people in Pensacola center now. If you guys want proof Bitcoin is real, send them to me, I’ll cash them out and feed homeless people. – Jason King",
    "The bitcoin world is this new ecosystem where it doesn’t cost that much to start a new Bitcoin company, it doesn’t cost much to start owning Bitcoin either, and it is a much more efficient way of moving money around the world. – Tim Draper",
    "Bitcoin enables certain uses that are very unique. I think it offers possibilities that no other currency allows. For example the ability to spend a coin that only occurs when two separate parties agree to spend the coin; with a third party that couldn’t run away with the coin itself. – Pieter Wuille",
    "Bitcoin is Cash with Wings – Charlie Shrem",
    "It was the amateurs of cryptology who created the species. The professionals, who almost certainly surpassed them in cryptanalytic expertise, concentrated on down-to-earth problems of the systems that were then in use but are now outdated. The amateurs, unfettered to those realities, soared into the empyrean of theory. – David Kahn",
    "Bitcoin is the currency of resistance. – Max Keiser",
    "What can’t kill Bitcoin, makes it stronger. – Mark Wittkowski",
    "You should be taking this technology as seriously as you should have been taking the development of the Internet in the early 1990’s. – Blythe Masters",
    "I think the internet is going to be one of the major forces for reducing the role of government. The one thing that’s missing but that will soon be developed is a reliable e-cash. –Milton Friedman",
    "What affected me most profoundly was the realization that the sciences of cryptography and mathematics are very elegant, pure sciences. I found that the ends for which these pure sciences are used are less elegant.  – Jim Sanborn",
    "Cryptography is the essential building block of independence for organizations on the Internet, just like armies are the essential building blocks of states because otherwise one state just takes over another. – Julian Assange",
    "Bitcoin was created to serve a highly political intent, a free and uncensored network where all can participate with equal access. – Amir Taaki",
    "Lots of people working in cryptography have no deep concern with real application issues. They are trying to discover things clever enough to write papers about. – Whitfield Diffie",
    "Trusted third parties are security holes. – Nick Szabo ",
    "This [Bitcoin] may be the purest form of democracy the world has ever known, and I — for one — am thrilled to be here to watch it unfold. – Paco Ahlgren",
    "Cryptography shifts the balance of power from those with a monopoly on violence to those who comprehend mathematics and security design.”  – Jacob Appelbaum",
    "[Cryptourrencies] may hold long-term promise, particularly if the innovations promote a faster, more secure and more efficient payment system. –Ben Bernanke",
    "Online identity and reputation will be decentralized. We will own the data that belongs to us. – William Mougayar",
    "It just identifies how much money laundering there is being done in the world,” Fink said. “How much people are trying to move currencies from one place to another. –Larry Fink",
    "Gold is a great way to preserve wealth, but it is hard to move around. You do need some kind of alternative and Bitcoin fits the bill. I’m not surprised to see that happening. – Jim Rickards",
    "What we want is fully anonymous, ultra-low transaction cost, transferable units of exchange. If we get that going… the banks will become the obsolete dinosaurs they deserve to become. – Adam Back",
    "The blockchain is an incorruptible digital ledger of economic transactions that can be programmed to record not just financial transactions but virtually everything of value. – Don & Alex Tapscott",
    "[Bitcoin is] the biggest opportunity set we can think of over the next decade. – Bob Grifeld",
    "Since we’re all rich with bitcoins … we ought to put some of this unearned wealth to good use. 67. Bitcoin seems to be a very promising idea. I like the idea of basing security on the assumption that the CPU power of honest participants outweighs that of the attacker. It is a very modern notion that exploits the power of the long tail.",
    "Bitcoin seems to be a very promising idea. I like the idea of basing security on the assumption that the CPU power of honest participants outweighs that of the attacker. It is a very modern notion that exploits the power of the long tail. 68. The computer can be used as a tool to liberate and protect people, rather than to control them.",
    "The computer can be used as a tool to liberate and protect people, rather than to control them. Satoshi Nakamoto Quotes",
    "Lost coins only make everyone else’s coins worth slightly more. Think of it as a donation to everyone. 70. Sigh… why delete a wallet instead of moving it aside and keeping the old copy just in case? You should never delete a wallet.",
    "Sigh… why delete a wallet instead of moving it aside and keeping the old copy just in case? You should never delete a wallet. 71. The possibility to be anonymous or pseudonymous relies on you not revealing any identifying information about yourself in connection with the bitcoin addresses you use. If you post your bitcoin address on the web, then you’re associating that address and any transactions with it with the name you posted under. If you posted under a handle that you haven’t associated with your real identity, then you’re still pseudonymous.",
    "The possibility to be anonymous or pseudonymous relies on you not revealing any identifying information about yourself in connection with the bitcoin addresses you use. If you post your bitcoin address on the web, then you’re associating that address and any transactions with it with the name you posted under. If you posted under a handle that you haven’t associated with your real identity, then you’re still pseudonymous. For greater privacy, it’s best to use bitcoin addresses only once.",
    "At the end of the day, Bitcoin is programmable money.",
    "One of my favorite words is a French word: sousveillance. It is the opposite of surveillance. Surveillance means to look from above; sousveillance means to look from below.",
    "One of my favorite words is a French word: sousveillance. It is the opposite of surveillance. Surveillance means to look from above; sousveillance means to look from below. 74. Bitcoin experts argue that deflation is not bad per se. Rather, deflation is associated with a collapse in demand because that is the only example of deflation we have to study.",
    "Bitcoin experts argue that deflation is not bad per se. Rather, deflation is associated with a collapse in demand because that is the only example of deflation we have to study. Less supportive quotes",
    "[Bitcoin is] worse than tulip bulbs – Jamie Dimon, CEO of JP Morgan",
    "Stay away from it. It’s a mirage, basically. In terms of cryptocurrencies, generally, I can say almost with certainty that they will come to a bad ending. –  Warren Buffett, legendary investor",
    "Bitcoin, and the ideas behind it, will be a disrupter to the traditional notions of currency. In the end, currency will be better for it. – Edmund Moy, 38th Director of the United States Mint",
    "Bitcoin is evil. – Paul Krugman, Nobel-prize winning economist"]
